name: swift-macros-security

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: swift-macros-security-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode for Tuist and Tuistenv
        run: sudo xcode-select -switch /Applications/15.0.1.app
      - name: Skip Xcode Macro Fingerprint Validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Build
        run: xcodebuild -project Executable/Executable.xcodeproj -scheme Executable clean build